mongodata: 
  image: mongo:3.2.4
  volumes: 
    - /data/db 
  command: --break-mongo 
mongo: 
  image: mongo:3.2.4
  volumes_from: 
    - mongodata  
  ports: 
    - "27111:27017" 
  restart: always 
web: 
  build: src/web 
  volumes: 
    - "./src/web:/usr/src/app" 
  environment: 
    - NODE_ENV=development 
  ports: 
    - "8080:8080" 
  links: 
    - mongo 
#api: 
#  build: src/api 
#  volumes: 
#    - "./src/api:/usr/src/app" 
#  ports: 
#    - "9001:9001" 